**What is NumPy?**

* NumPy is a Python library used for working with arrays.

* NumPy stands for Numerical Python.

**Why Use NumPy?**

* In Python we have lists that serve the purpose of arrays, but they are slow to process.

* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

* The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

* Arrays are very frequently used in data science and machine learning, where speed and resources are very important.

In [2]:
# Installation of NumPy in our Python Environment

# Installation of NumPy in our Python Environment

# Just run the command

!pip install numpy

In [3]:
import numpy as np

**Create a NumPy ndarray Object**

* NumPy is used to work with arrays. The array object in NumPy is called ndarray.

* We can create a NumPy ndarray object by using the array() function.

In [4]:
numpy_array = np.array([1, 2, 3, 4, 5])

print(numpy_array)

print(type(numpy_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
numpy_array[0]

1

In [6]:
numpy_array[0] + numpy_array[1]

3

In [11]:
numpy_array[-1]

5

In [15]:
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


In [13]:
zeros_array = np.zeros((2, 3))

print("Zeros Array:\n", zeros_array)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
ones_array = np.ones((3, 2))

print("Ones Array:\n", ones_array)

Ones Array:
 [[ 1.0  1.0]
 [ 1.0  1.0]
 [ 1.0  1.0]]


In [22]:
print("Shape of Ones Array:", ones_array.shape)

Shape of Ones Array: (3, 2)


In [24]:
print("Data Type of Array:", zeros_array.dtype)

Data Type of Array: float64


In [8]:
array_1d = np.array([1, 2, 3, 4, 5])
print("Number of Dimensions:", array_1d.ndim)

Number of Dimensions: 1


In [28]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print(f'Total Elements in the Array: {array_2d.size}')

Total Elements in the Array: 6


In [30]:
array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("First Element of 1D Array:", array_1d[0])

print(array_2d)

print("Element at Row 1, Column 2 of 2D Array:", array_2d[1, 2])

First Element of 1D Array: 1
[[1 2 3]
 [4 5 6]]
Element at Row 1, Column 2 of 2D Array: 6


In [81]:
array_1d = np.array([1, 2, 3, 4, 5])

array_2d = np.array([[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 10], [10, 11, 12, 13]])

print("Slicing 1D Array (first three elements):\n", array_1d[2:])

print("Array 2D Looks something like this: \n", array_2d)

print("Slicing 2D Array (first row):\n", array_2d[2:3, 2:3])

Slicing 1D Array (first three elements):
 [3 4 5]
Array 2D Looks something like this: 
 [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]
 [10 11 12 13]]
Slicing 2D Array (first row):
 [[9]]


In [92]:
flattened_array = array_2d.flatten()

print("Flattened Array:", flattened_array)

Flattened Array: [ 1  2  3  4  4  5  6  7  7  8  9 10 10 11 12 13]


In [97]:
array_a = np.array([[1, 2], [3, 4]])
array_b = np.array([[5, 6]])
concatenated_array = np.concatenate((array_a, array_b))
print("Concatenated Array:\n", concatenated_array)

Concatenated Array:
 [[1 2]
 [3 4]
 [5 6]]


In [99]:
sum_array = array_a + array_b

print("Sum Array:\n", sum_array)

Sum Array:
 [[ 6  8]
 [ 8 10]]
