In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [4]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42
arr[1] = 32

print(arr)
print(x)

[42 32  3  4  5]
[42 32  3  4  5]


In [5]:
arr = np.array([1, 2, 3, 4, 5])

for x in arr:
  print(x)

1
2
3
4
5


In [6]:
arr = np.array([[1,2, 3, 4, 5, 6, 7, 8], [6, 7, 8, 9, 10, 11, 12, 13]])

for x in arr:
  print(x)


[1 2 3 4 5 6 7 8]
[ 6  7  8  9 10 11 12 13]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

for a in x:
  print(arr[a])

(array([3, 5, 6]),)
[4 4 4]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

for a in x:
  print(arr[a])

(array([1, 3, 5, 7]),)
[2 4 6 8]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

(array([0, 2, 4, 6]),)


In [12]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [13]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [14]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


**Filtering Arrays**

Getting some elements out of an existing array and creating a new array out of them is called filtering.

In [15]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [16]:
arr = np.array([41, 42, 43, 44])

filter_arr = []

for x in arr:
  if x >= 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False, True, True, True]
[42 43 44]


In [17]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = []

for element in arr:
  if element % 2 == 0:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(arr)
print(filter_arr)
print(newarr)

[1 2 3 4 5 6 7]
[False, True, False, True, False, True, False]
[2 4 6]


In [18]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(arr)
print(filter_arr)
print(newarr)

[41 42 43 44]
[False False  True  True]
[43 44]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

In [ ]:
!pip install pandas

In [19]:
import pandas as pd

iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)
data = iris.to_numpy()
print("FIRST 5 ROWS:\n", data[:5])

FIRST 5 ROWS:
 [[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]


**UNDERSTANDING THE DATA**

In [20]:
print("THE SHAPE OF THE DATA: ", data.shape)

THE SHAPE OF THE DATA:  (150, 5)


In [21]:
print("THE SIZE OF THE DATA: ", data.size)

THE SIZE OF THE DATA:  750


In [22]:
print("DATA TYPE OF DATASET: ", data.dtype)

DATA TYPE OF DATASET:  object


In [23]:
print("THE FIRST FIVE ROWS OF THE DATA: \n")
print("FOR COLUMN INSPECTION!")

print(data[:5])

THE FIRST FIVE ROWS OF THE DATA: 

FOR COLUMN INSPECTION!
[[5.1 3.5 1.4 0.2 'Iris-setosa']
 [4.9 3.0 1.4 0.2 'Iris-setosa']
 [4.7 3.2 1.3 0.2 'Iris-setosa']
 [4.6 3.1 1.5 0.2 'Iris-setosa']
 [5.0 3.6 1.4 0.2 'Iris-setosa']]


In [24]:
df = pd.DataFrame(data)
print("THE FIRST FIVE ROWS OF THE DATA: \n")
print("FOR COLUMN INSPECTION!")
print(df.head())

THE FIRST FIVE ROWS OF THE DATA: 

FOR COLUMN INSPECTION!
     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa


In [25]:
features = data[:, :-1].astype(float)
labels = data[:, -1]

print("Features (first 5 rows):\n", features[:5], "\n")
print("Labels (first 5 rows):\n", labels[:5])


Features (first 5 rows):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]] 

Labels (first 5 rows):
 ['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [26]:
# The mean can be used to fill in missing values in a dataset,
# A common preprocessing step.

print("Mean of each feature:", np.mean(features, axis=0))

Mean of each feature: [5.84333333 3.054      3.75866667 1.19866667]


In [27]:
feature_means = np.mean(features, axis=0)

mean_str = ', '.join(f'{mean:.2f}' for mean in feature_means)

print("Mean of each feature:", mean_str)

Mean of each feature: 5.84, 3.05, 3.76, 1.20


**Extracting the minimum value of each column is valuable for understanding the data's range, distribution, and potential outliers.**

In [28]:
print("Minimum value of each feature:", np.min(features, axis=0))

Minimum value of each feature: [4.3 2.  1.  0.1]


In [ ]:
features_mins = np.min(features, axis=0)

min_str = ', '.join(f'{min:.2f}' for min in features_mins)

print("Minimum value of each feature:", min_str)

In [29]:
print("Maximum value of each feature:", np.max(features, axis=0))

Maximum value of each feature: [7.9 4.4 6.9 2.5]


In [ ]:
features_maxs = np.max(features, axis=0)

max_str = ', '.join(f'{max:.2f}' for max in features_maxs)

print("Maximum value of each feature:", max_str)

In [32]:
unique_labels, label_counts = np.unique(labels, return_counts=True)
print("Unique labels:\n", unique_labels, "\n")
print("Counts of each label:\n", label_counts)

Unique labels:
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica'] 

Counts of each label:
 [50 50 50]


In [33]:
missing_features = np.isnan(features).any(axis=0)

print("Missing values in features:", missing_features)

Missing values in features: [False False False False]


In [ ]:
missing_labels = (labels == '').any()

print("Missing values in labels:", missing_labels)

In [35]:
unique_labels, encoded_labels = np.unique(labels, return_inverse=True)
print("Encoded labels (first 5):", encoded_labels[:])

Encoded labels (first 5): [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
